### PR TITLE
Remove simple

### PR DESCRIPTION
**Pull request by JRIngram**
Removed the simple variable as its functionality could be managed by the ptype / password_type variable. 

Consequently update_password_type was no longer needed, as simple had been removed, and as such update_password_type has now been removed.

### CODE REVIEW

**Comment by JRIngram** [comment]
This builds on the documentation pull request.

**Comment by Samusoidal** [comment]
Yeah, I literally made this in 30 minutes at work. It's pretty terrible, thanks for your interest!

As long as we're adding docstrings we should follow the PEP guide and put them inside the functions.

**Comment by JRIngram** [comment]
>As long as we're adding docstrings we should follow the PEP guide and put them inside the functions.

I'll have a review of the style guide and rewrite / move the docstrings! Sorry fairly new to Python (only really use it in a hobbyist settings) so I'm still getting used to conventions! I'll aim to get them done this weekend, most likely Sunday!

> thanks for your interest!

No worries, I'm surprised at how little Dinopass programs there are on GitHub to be honest!

**Comment by JRIngram** [comment]
Hi Samusoidal,

I've moved Docstring inside functions and changed comments from ''' to #.

**Pull request merged**
